In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
tf.random.set_seed(42)

In [ ]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [ ]:
x_data = np.array([[h]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.]]], dtype=float32)

In [ ]:
x_data.shape

(1, 1, 4)

In [ ]:
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.31773362 -0.11744198]]] 	 shape : (1, 1, 2)
states : [[ 0.31773362 -0.11744198]] 	 shape : (1, 2)


In [ ]:
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=False)
output = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.54152584 -0.00444528]]] 	 shape : (1, 1, 2)


In [ ]:
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=False, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[-0.12818007  0.04968958]] 	 shape : (1, 2)
states : [[-0.12818007  0.04968958]] 	 shape : (1, 2)


In [ ]:
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.14876226 -0.53846276]]] 	 shape : (1, 1, 2)
states : [[ 0.14876226 -0.53846276]] 	 shape : (1, 2)


In [ ]:
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [ ]:
x_data.shape

(1, 5, 4)

In [ ]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]] 	 shape : (1, 5, 4)
output : [[[ 0.168862    0.75540954]
  [ 0.3763032  -0.13249622]
  [ 0.6409074   0.59663606]
  [ 0.9107355   0.6422901 ]
  [-0.05642458  0.52916396]]] 	 shape : (1, 5, 2)
states : [[-0.05642458  0.52916396]] 	 shape : (1, 2)


In [ ]:
x_data = np.array([[h, e, l, l, o], [e, o, l, l, l], [l, l, e, e, l]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)

In [ ]:
x_data.shape

(3, 5, 4)

In [ ]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]] 	 shape : (3, 5, 4)
output : [[[ 0.05686769  0.34700885]
  [ 0.5258374  -0.33018067]
  [ 0.83039427 -0.7154057 ]
  [ 0.9328015  -0.72991735]
  [ 0.9380278   0.44018933]]

 [[ 0.6841841  -0.09805116]
  [ 0.785885    0.30606773]
  [ 0.67244357 -0.9004724 ]
  [ 0.9403924  -0.6000644 ]
  [ 0.9285215  -0.79493284]]

 [[ 0.549907   -0.57478976]
  [ 0.88622147 -0.65178597]
  [ 0.9542981  -0.42552215]
  [ 0.93915325 -0.5644942 ]
  [ 0.9242802  -0.8019193 ]]] 	 shape : (3, 5, 2)
states : [[ 0.9380278   0.44018933]
 [ 0.9285215  -0.79493284]
 [ 0.9242802  -0.8019193 ]] 	 shape : (3, 2)


In [4]:
idx2char = ['토', '마', '를', '먹', '자' ]

x_data = [[0, 0, 1, 2, 4, 3]] #토 토 마 를 자 먹
y_data = [[0, 1, 0, 2, 3, 4]] #토 마 토 를 먹 자

num_classes = 5
input_dim = 5
sequence_len = 6
learning_rate = 0.1

x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=num_classes)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)

print(x_one_hot)
print(x_one_hot.shape)
print(y_one_hot)
print(y_one_hot.shape)

[[[1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0.]]]
(1, 6, 5)
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]
(1, 6, 5)


In [5]:
from tensorflow.keras.models import Model

model = tf.keras.Sequential()
cell = layers.SimpleRNNCell(units=num_classes, input_shape=(sequence_len, input_dim))

model.add(layers.SimpleRNN(units=num_classes, return_sequences=True, return_state=False, input_shape= (sequence_len, input_dim)))
# model.add(layers.RNN(cell=cell, return_sequences=True, return_state=False, input_shape= (sequence_len, input_dim)))
model.add(layers.TimeDistributed(layers.Dense(units=num_classes, activation='softmax')))

model.compile(loss='categorical_crossentropy', 
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 6, 5)              55        
_________________________________________________________________
dense (Dense)                (None, 6, 5)              30        
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.fit(x_one_hot, y_one_hot, epochs=10)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 1.7280 - accuracy: 0.3333
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 1.3304 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 1.1051 - accuracy: 0.6667
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 0.9659 - accuracy: 0.8333
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 0.8458 - accuracy: 0.8333
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.7280 - accuracy: 0.8333
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6179 - accuracy: 0.8333
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5319 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.4592 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 0.3887 - accuracy: 1.0000


In [7]:
pred = model.predict(x_one_hot)
pred

array([[[7.5631112e-01, 1.4465895e-01, 3.8438611e-02, 2.7743693e-02,
         3.2847572e-02],
        [1.8408325e-01, 5.3597862e-01, 2.1356136e-01, 6.4031266e-02,
         2.3455545e-03],
        [9.1988701e-01, 3.9871383e-02, 1.9777099e-02, 1.7813803e-03,
         1.8683027e-02],
        [9.1766737e-02, 3.5670412e-01, 4.6275312e-01, 8.7967366e-02,
         8.0866780e-04],
        [1.4649854e-02, 3.5932403e-02, 2.3643360e-02, 8.8369137e-01,
         4.2082965e-02],
        [4.8947319e-02, 3.0662518e-03, 7.0957444e-04, 9.4018262e-03,
         9.3787497e-01]]], dtype=float32)

In [8]:
for i, word in enumerate(pred):
    print(" ".join([idx2char[c] for c in np.argmax(word, axis=1)]))

토 마 토 를 먹 자
