# 실기문제 1

In [20]:
docs = ['우리반은 마라탕을 좋아해',
'우리반은 마라탕을 더 이상 먹지않을거야 그래도 마라탕을 좋아해']

In [24]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['우리반은', '마라탕을', '좋아해'],
 ['우리반은', '마라탕을', '더', '이상', '먹지않을거야', '그래도', '마라탕을', '좋아해']]

In [25]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id


defaultdict(<function __main__.<lambda>()>,
            {'우리반은': 0,
             '마라탕을': 1,
             '좋아해': 2,
             '더': 3,
             '이상': 4,
             '먹지않을거야': 5,
             '그래도': 6})

In [26]:
import numpy as np 

TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)
for i, doc in enumerate(doc_ls):
  for token in doc:
    TDM[word2id[token], i] += 1
TDM

array([[1, 1],
       [1, 2],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [27]:
import pandas as pd

doc_name = ['문서{}'.format(i) for i in range(len(doc_ls))]
sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns=doc_name)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1
단어              
우리반은      1    1
마라탕을      1    2
좋아해       1    1
더         0    1
이상        0    1
먹지않을거야    0    1
그래도       0    1

# 실기문제2

## DTM 생성

In [29]:
import numpy as np 

DTM = np.zeros((len(doc_ls), len(word2id)), dtype=int)
for i, doc in enumerate(doc_ls):
  for token in doc:
    DTM[i, word2id[token]] += 1
DTM

array([[1, 1, 1, 0, 0, 0, 0],
       [1, 2, 1, 1, 1, 1, 1]])

## TF 계산

In [31]:
def computeTF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])
  tf = np.zeros((doc_len, word_len))
  for doc_idx in range(doc_len):
    for word_idx in range(word_len):
      tf[doc_idx, word_idx] = DTM[doc_idx, word_idx]/DTM[doc_idx].sum()

  return tf

computeTF(DTM)

array([[0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
        0.        , 0.        ],
       [0.125     , 0.25      , 0.125     , 0.125     , 0.125     ,
        0.125     , 0.125     ]])

## IDF 계산

In [37]:
import math

def computeIDF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])
  idf = np.zeros(word_len)
  for i in range(word_len):
    idf[i] = -math.log10(np.count_nonzero(DTM[:, i])/doc_len)

  return idf
      
computeIDF(DTM)    

array([-0.     , -0.     , -0.     ,  0.30103,  0.30103,  0.30103,
        0.30103])

TF-IDF 계산

In [34]:
def computeTFIDF(DTM):
  tf = computeTF(DTM)
  idf = computeIDF(DTM)

  # tfidf = tf*idf #broadcasting

  tfidf = np.zeros(tf.shape)
  for doc_idx in range(tf.shape[0]):
    for word_idx in range(tf.shape[1]):
      tfidf[doc_idx, word_idx] = tf[doc_idx, word_idx] * idf[word_idx]

  return tfidf

  
computeTFIDF(DTM)

array([[-0.        , -0.        , -0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-0.        , -0.        , -0.        ,  0.03762875,  0.03762875,
         0.03762875,  0.03762875]])

In [35]:
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
tfdif = computeTFIDF(DTM)
pd.DataFrame(tfdif, columns=vocab)

우리반은  마라탕을  좋아해         더        이상    먹지않을거야       그래도
0  -0.0  -0.0 -0.0  0.000000  0.000000  0.000000  0.000000
1  -0.0  -0.0 -0.0  0.037629  0.037629  0.037629  0.037629

## 실기문제3 - 자카드유사도

In [41]:
from konlpy.tag import Mecab
mecab = Mecab()

# 문장간 유사도 측정 (자카드 유사도 사용)
def sentence_similarity(sentence1, sentence2):
  sentence1 = [token[0] for token in mecab.pos(sentence1) if token[1][0] in ['N', 'V']] 
  sentence2 = [token[0] for token in mecab.pos(sentence2) if token[1][0] in ['N', 'V']]

  union = set(sentence1).union(set(sentence2))
  intersection = set(sentence1).intersection(set(sentence2))

  return len(intersection)/len(union)
  

sentence_similarity(docs[0],docs[1])

0.4166666666666667

## 실기문제 4

math.log()

math.log()


math.log()

math.log()


math.exp()

math.exp()